enum_discrim_align_threshold = 40
fn_args_layout = "Tall"
hard_tabs = false
indent_style = "Visual"
match_block_trailing_comma = true
max_width = 80
overflow_delimited_expr = true
use_field_init_shorthand = true
